### ISSUE TITLE
Replace ppp category with more precise categories?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/extension_registry#106]
13 community extensions have the category `ppp`, but can be given more precise categories like `planning`, `budget`, etc. We may want to review whether any are worth surfacing outside the PPP profile.

**Comment by jpmckinney** [comment]
Tagging @duncandewhurst for thoughts, given recent work on PPP profile.

**Comment by duncandewhurst** [comment]
Off the top of my head, some of the extensions in the `ppp` category are specific to the PPP profile in either their nature or way they have been documented (e.g. risk allocation, charges) whilst others could be worth surfacing outside the PPP profile (e.g. documentation details).

I don't think the `ppp` category is needed to pull extensions in to the PPP profile build, so the categories could be made more precise without actually breaking anything, but since the categories are only used to pull in core extensions to the main standard docs I'm not sure what the benefit of that would be (all the `ppp` extensions are community extensions) and I don't think we'd want to lose the view of which extensions are specific to a certain profile (particularly as we add more profiles).

**Comment by jpmckinney** [comment]
The categories are also used to pull in community extensions (via JavaScript), e.g. find occurrences of "The following are community extensions and are not maintained by Open Contracting Partnership." on [this page](http://standard.open-contracting.org/latest/en/schema/reference/#tender). (I also forgot that community extensions were pulled in this way.)

For the extensions that are specific to PPP, it makes sense for the category to be PPP. But since community extensions appear in the standard documentation based on category, would any of these deserve a broader category?

* budget
* budget_project
* documentation_details
* finance
* metrics
* qualification
* shareholders
* tariffs
* transaction_milestones

The following community extensions in OCDS for PPPs already have a non-`ppp` category:

* performance_failures (implementation)
* requirements (tender)
* signatories (contract)

The following extensions with category `ppp` were described as specific to OCDS for PPPs:

* charges
* risk_allocation

**Comment by timgdavies** [comment]
Looking through the list, the only one I'm confident we have had cause to suggest to people outside of the PPP context so far, is 'documentation_details' (although we don't currently have a section in the [reference docs](http://standard.open-contracting.org/latest/en/schema/reference/#document) to pull in things tagged as 'documentation' or extending the 'documentation' building block)

The others are *potentially* useful beyond PPPs, but I suggest we loop back to identify additional categorisations we should add once we have new front-end of extensions registry coming together if that makes sense?

**Comment by jpmckinney** [comment]
Makes sense! I'll close in favor of letting the work on the extensions explorer determining future iterations on categories.
