### ISSUE TITLE
Changes for MVP

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/extension_registry#85]
Changes to system of entries:

* [x] Consider a single CSV for all entries, instead of directories of entry.json files (harder to navigate, review, analyze, etc.)
* [x] Consider removing fields that are duplicating extension.json: description, documentationUrl, name, dependencies, compatibility (i.e. leaving category, core, url, slug, version)
* [x] Based on the above, update entry-schema.json (which may be used to validate a CSV, like codelist-schema.json does), README.md, compile.py
* [x] Update compile.py to validate uniqueness of "slug"
* [x] Delete new.py

Additional changes to entries:

* [x] Add enum for "category" in entry-schema.json (based on `extensionlist` directive) #99
* [ ] Add "downloadUrl" to entry-schema.json for link to ZIP file
* [x] Add "author" and "authorEmail" #97

Changes to resources that depend on current registry layout:

* [x] Update "Reviewing an extension registry entry" in https://docs.google.com/document/d/1bRhVVkuTPXw6acE2opKD-Yj80y0lvAsfAqDjG632nNY/edit

**Comment by jpmckinney** [comment]
Noting that I may implement this at any moment, as working with the present registry is a nightmare, especially as I will have to draft multiple extensions for GPA, EU, etc.

FYI @robredpath @Bjwebb @kindly

**Comment by robredpath** [comment]
Thanks for the heads-up @jpmckinney . Can we talk about this when we're talking about docs refactoring on Monday? Extension registry design is something we've given some thought to so it'd be good to cross-check this.

**Comment by jpmckinney** [comment]
Sounds good – this largely follows from a discussion I had with Ben, David and Tim in London.

**Comment by robredpath** [comment]
@kindly just had a chat with @jpmckinney and @Bjwebb about this - the only substantive change from your discussions has been the addition of the CSV file for the entries, I think. Can you give your thoughts on that in this issue? I know you've done a lot of the thinking around this!

**Comment by robredpath** [comment]
We said during planning that this and #86 felt like tasks that came out of a larger vision that we didn't feel we had a grip on and so couldn't see how it all fell into place. So, we asked @jpmckinney during our regular call today, and these are my notes on what he told us:

- we want some place we can list core and community (but not local) extensions to allow people to discover them
- we found some issues, especially with automation
- we're creating lots more extensions
- we want to avoid duplication of content in extensions, but there's a lot at the moment
- the idea is to document the extensions separately from the code and follow the pattern of OCDS profiles (we'll hear from @duncandewhurst more about this shortly!) 
- we can then build all of the versions at once
- At the moment, you have to build all of the extensions to get docs for all of them

- A new registry would need to list versions. 
- It's complicated and hard to find extensions across all branches
- So, we should replace this system, avoid duplication and the risk of docs getting out of date
- A CSV of all versions of extensions would only contain data not in the extensions themselves, and would give us just one file to maintain 

We asked about extension review before acceptance:
- we already have some docs - https://docs.google.com/document/d/1bRhVVkuTPXw6acE2opKD-Yj80y0lvAsfAqDjG632nNY/edit
- we're still improving the process, and it's not been used much. It's a mix of manual and automatic tests. 
- Once people have had their extension reviewed once they're largely trusted to maintain it to a good standard. Most people don't release versions, just push to master. We could encourage people to do releases, but we'd need to check with @timgdavies on governance issues

**Comment by odscjames** [comment]
See #90 for work on this - I will post more on that P.R. soon.

**Comment by odscjames** [comment]
This work has been largely done across different tickets. There is now one branch, one csv, de-duped values in the master branch.

- #91 is a follow up for de-dupe work.
- #92 is a follow up for extra validation. (ticked "update entry-schema.json" above as that will now be dealbt with on this ticket)
- #94 is a follow up for some more tests and travis notes.


Notes on unticked things

- Add enum for "category" in entry-schema.json (based on extensionlist directive) - this might be dealbt with in #92 
- Add "downloadUrl" to entry-schema.json for link to ZIP file - this is about allowing extensions to be ZIP files online and not in git. The discussion on this has moved on so that isn't relevant directly now but the general point may be picked up soon.
- Add "author" and "authorEmail" - Do we still want to do this? I guess it should be done in https://github.com/open-contracting/standard_extension_template/blob/master/extension.json and the appropriate JSON Schema. This way extension authors can edit these values themselves - changes probably don't require approval. If still wanted I'll spin this off to a new ticket.

Updating instructions - I will check on those.

Later work - I amagine this will be looked at as part of #86

**Comment by odscjames** [comment]
I have suggested edits on "Reviewing an extension registry entry"

**Comment by jpmckinney** [comment]
Yes, good call to have author and authorEmail in each extension. Such fields mirror packaging systems; whereas, for our extensions, people may know to contact the OCDS helpdesk, for government-published extensions, there is likely no way to contact that government except through GitHub issues, which may not be monitored, based on my experience working on dozens of government repositories via GitHub.

**Comment by jpmckinney** [comment]
I moved the remaining unticketed items to #102, so this is now closed :)
